{% set version = "1.6" %}

package:
  name: dm-env
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dm-env/dm-env-{{ version }}.tar.gz
  sha256: a436eb1c654c39e0c986a516cee218bea7140b510fceff63f97eb4fcff3d93de

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - absl-py
    - dm-tree
    - numpy
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - dm_env
  commands:
    - pip check
    - pytest -vv --pyargs dm_env --cov=dm_env --cov-report=term-missing:skip-covered --cov-fail-under=98

about:
  home: https://pypi.org/project/dm-env
  summary: A Python interface for Reinforcement Learning environments.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/deepmind/dm_env
  doc_url: https://github.com/deepmind/dm_env/blob/{{ version }}/docs/index.md

extra:
  recipe-maintainers:
    - bollwyvl
